require('which-key').setup()
-- local whichkey = require('which-key')
--
-- whichkey.setup()
--
-- whichkey.add {
--   { '<leader>c', group = '[C]ode' },
--   { '<leader>d', group = '[D]ocument' },
--   { '<leader>r', group = '[R]ename' },
--   { '<leader>s', group = '[S]earch' },
--   { '<leader>w', group = '[W]orkspace' },
--   { '<leader>t', group = '[T]oggle' },
--   { '<leader>h', group = 'Git [H]unk', mode = { 'n', 'v' } },
-- }
